[environment]
python = "C:/Users/kp301/AppData/Local/Programs/Python/Python313/python.exe"
search-paths = [
    ".",
    "C:/Users/kp301/AppData/Local/Programs/Python/Python313/Lib/site-packages",
    "sms_shared_core"
]

[errors]
missing-attribute = "ignore"
untyped-import = "ignore"
