# Generated by Django 6.0.3 on 2026-06-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leavetemplate",
            name="staff",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="sms_app.staff",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leavetemplate",
            name="time_line",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
