# Generated by Django 6.0.3 on 2026-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffremainingleave",
            name="month",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="staffremainingleave",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
