# Generated by Django 6.0.3 on 2026-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="latebookfees",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
