# Generated by Django 6.0.3 on 2026-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_latebookfees_grace_period_days"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentParent",
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="month",
            field=models.IntegerField(default=7),
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
    ]