# Generated by Django 6.0.3 on 2026-06-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_staffremainingleave_month_staffremainingleave_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffremainingleave",
            name="month",
        ),
        migrations.RemoveField(
            model_name="staffremainingleave",
            name="year",
        ),
    ]
