# Generated by Django 6.0.3 on 2026-06-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_staffremainingleave_month_staffremainingleave_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavetype",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
    ]
