# Generated by Django 6.0.3 on 2026-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0002_leaverequest_status_leavetemplate_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffremainingleave",
            name="month",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffremainingleave",
            name="year",
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PARTIAL", "Partial"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
