# Generated by Django 6.0.3 on 2026-06-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_staffremainingleave_month_staffremainingleave_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffremainingleave",
            unique_together={("staff", "leave_template", "month", "year")},
        ),
        migrations.AddField(
            model_name="staffremainingleave",
            name="total_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="leave_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.leavetemplate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="remaining_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.staff",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="staffremainingleave",
            name="total_levaes",
        ),
    ]
