# Generated by Django 6.0.3 on 2026-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0003_alter_leavetype_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelocation",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
