# Generated by Django 6.0.3 on 2026-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_alter_staffremainingleave_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffremainingleave",
            name="carry_forward_leaves",
            field=models.IntegerField(default=0),
        ),
    ]
