# Generated by Django 6.0.3 on 2026-06-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0004_attendancelocation_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancelocation",
            name="start_time",
        ),
        migrations.AddField(
            model_name="attendancelocation",
            name="time_rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.attendancetimerule",
            ),
        ),
    ]
