# Generated by Django 6.0.3 on 2026-06-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_remove_leaverequest_leave_type_fk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.student",
            ),
        ),
    ]
