# Generated by Django 6.0.3 on 2026-06-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_staffremainingleave_carry_forward_leaves"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_image", models.ImageField(upload_to="staff-faces/")),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face",
                        to="sms_app.staff",
                    ),
                ),
            ],
        ),
    ]
