# Generated by Django 6.0.3 on 2026-06-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_remove_leaverequest_leave_type_fk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExamNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_image", models.ImageField(upload_to="staff-faces/")),
                ("is_enrolled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESULT", "Result"),
                            ("REPORT_CARD", "Report Card"),
                            ("CERTIFICATE", "Certificate"),
                            ("ACHIEVEMENT", "Achievement"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("document", models.FileField(upload_to="student_documents/")),
                ("is_visible_to_parent", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "student_document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE", "Attendance"),
                            ("PROGRESS", "Progress"),
                            ("DOCUMENT", "Document"),
                            ("EXAM", "Exam"),
                            ("HOMEWORK", "Homework"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_parent",
            },
        ),
        migrations.RemoveField(
            model_name="certificaterequest",
            name="certificate_type",
        ),
        migrations.RemoveField(
            model_name="certificaterequest",
            name="school",
        ),
        migrations.RemoveField(
            model_name="certificatetype",
            name="school",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="school",
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="leavetemplate",
            name="leave_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="leavetemplate",
            name="unique_staff_leave_type",
        ),
        migrations.RemoveField(
            model_name="attendancelocation",
            name="time_rule",
        ),
        migrations.AlterUniqueTogether(
            name="staffremainingleave",
            unique_together={("staff", "leave_template", "year")},
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PARTIAL", "Partial"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.AddField(
            model_name="staffremainingleave",
            name="carry_forward_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staffremainingleave",
            name="total_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="leavetemplate",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="sms_app.staff",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leavetemplate",
            name="time_line",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="leave_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.leavetemplate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="remaining_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.staff",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="exam",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.schoolclass"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.staff"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.school"
            ),
        ),
        migrations.AddField(
            model_name="examnotification",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.exam"
            ),
        ),
        migrations.AddField(
            model_name="staffface",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face",
                to="sms_app.staff",
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sms_app.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.school"
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_documents",
                to="sms_app.student",
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="sms_app.staff",
            ),
        ),
        migrations.AddField(
            model_name="studentnotification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sms_app.staff",
            ),
        ),
        migrations.AddField(
            model_name="studentnotification",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.school"
            ),
        ),
        migrations.AddField(
            model_name="studentnotification",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="sms_app.student",
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_mappings",
                to="sms_app.parent",
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_mappings",
                to="sms_app.student",
            ),
        ),
        migrations.DeleteModel(
            name="CertificateRequest",
        ),
        migrations.DeleteModel(
            name="CertificateType",
        ),
        migrations.DeleteModel(
            name="LeaveType",
        ),
        migrations.RemoveField(
            model_name="staffremainingleave",
            name="month",
        ),
        migrations.RemoveField(
            model_name="staffremainingleave",
            name="total_levaes",
        ),
        migrations.AlterUniqueTogether(
            name="studentparent",
            unique_together={("student", "parent")},
        ),
    ]
