# Generated by Django 6.0.3 on 2026-07-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0005_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="publish_at",
        ),
        migrations.AddField(
            model_name="announcement",
            name="announcement_for",
            field=models.CharField(
                choices=[
                    ("Teacher", "teacher"),
                    ("Clerk", "clerk"),
                    ("Fee-manager", "fee-manager"),
                    ("Librarian", "librarian"),
                    ("Student", "student"),
                    ("Parent", "parent"),
                ],
                default="Teacher",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_everyone",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="description",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="AnnouncementTarget",
        ),
    ]
