# Generated by Django 6.0.3 on 2026-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_remove_announcement_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
