# Generated by Django 6.0.3 on 2026-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_staffface"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffface",
            old_name="is_verified",
            new_name="is_enrolled",
        ),
    ]
