# Generated by Django 6.0.3 on 2026-06-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0006_exam_examnotification_staffface_studentdocument_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeworksubmission",
            options={},
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="checked_at",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="checked_by",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="school",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="status",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="teacher_remark",
        ),
        migrations.RemoveField(
            model_name="homeworksubmission",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="attendancelocation",
            name="time_rule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.attendancetimerule",
            ),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="file",
            field=models.FileField(default=1, upload_to="homework_submissions/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.homework"
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="sms_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
            
        ),
        migrations.AlterField(
            model_name="leavetemplate",
            name="time_line",
            field=models.CharField(default="MONTHLY", max_length=20),
        ),
        migrations.AlterModelTable(
            name="homeworksubmission",
            table=None,
        ),
        migrations.CreateModel(
            name="CertificateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_type",
            },
        ),
        migrations.CreateModel(
            name="CertificateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.certificatetype",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_request",
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "leave_type",
            },
        ),
    ]
