# Generated by Django 6.0.3 on 2026-06-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_certificate"),
    ]

    operations = [

        migrations.RunSQL(
            sql="""
                ALTER TABLE leave_template
                DROP CONSTRAINT IF EXISTS unique_staff_leave_type;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # LeaveType changes
        migrations.RemoveField(
            model_name="leavetype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="school",
        ),

        migrations.AddField(
            model_name="leavetype",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.schoolfeature",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="leave_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="leave_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.leavetemplate",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="leave_type",
            field=models.CharField(max_length=100, null=True),
        ),

        # LeaveTemplate changes
        migrations.AddField(
            model_name="leavetemplate",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.AlterField(
            model_name="leavetemplate",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),

        migrations.AlterField(
            model_name="leavetemplate",
            name="time_line",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("SEMI_ANNUAL", "Semi-Annual"),
                    ("ANNUAL", "Annual"),
                ],
                max_length=20,
                null=True,
            ),
        ),

        migrations.RemoveField(
            model_name="leavetemplate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="leavetemplate",
            name="leave_num",
        ),
        migrations.RemoveField(
            model_name="leavetemplate",
            name="leave_type",
        ),
        migrations.RemoveField(
            model_name="leavetemplate",
            name="staff",
        ),
    ]