# Generated by Django 6.0.3 on 2026-06-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_certificaterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
    ]
