# Generated by Django 6.0.3 on 2026-06-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_exam_examnotification_staffface_studentdocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("discipline", models.PositiveSmallIntegerField(default=0)),
                ("communication_skills", models.PositiveSmallIntegerField(default=0)),
                ("emotional_development", models.PositiveSmallIntegerField(default=0)),
                ("social_development", models.PositiveSmallIntegerField(default=0)),
                ("freindly_with_others", models.PositiveSmallIntegerField(default=0)),
                ("remark", models.TextField(max_length=100)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "monthly_progress_report",
                "ordering": ["-created_at"],
            },
        ),
        
        
        migrations.AddField(
            model_name="monthlyprogressreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.staff"
            ),
        ),
        migrations.AddField(
            model_name="monthlyprogressreport",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms_app.school"
            ),
        ),
        migrations.AddField(
            model_name="monthlyprogressreport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_reports",
                to="sms_app.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyprogressreport",
            unique_together={("student", "month", "year")},
        ),
    ]
