# Generated by Django 6.0.3 on 2026-07-06 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_alter_announcement_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificatetype",
            name="template_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CertificateFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.SlugField(blank=True, max_length=100)),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Long Text"),
                            ("date", "Date"),
                            ("number", "Number"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "certificate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="sms_app.certificatetype",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_field_definition",
                "ordering": ["order", "id"],
                "unique_together": {("certificate_type", "field_name")},
            },
        ),
    ]
