# Generated by Django 6.0.3 on 2026-07-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_certificate_data_certificate_generated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="expires_at",
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="announcement_for",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEACHER", "Teacher"),
                    ("CLERK", "Clerk"),
                    ("FEE-MANAGER", "Fee-manager"),
                    ("LIBRARIAN", "Librarian"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
