# Generated by Django 6.0.3 on 2026-06-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_remove_leavetemplate_unique_staff_leave_type_and_more"),
    ]

    operations = [

        # ✅ SAFE DROP (fixes your crash)
        migrations.RunSQL(
            sql="""
                ALTER TABLE leave_template
                DROP CONSTRAINT IF EXISTS unique_staff_leave_type;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ForeignKey update
        migrations.AlterField(
            model_name="leavetype",
            name="leave_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_types",
                to="sms_app.leavetemplate",
            ),
        ),

        # New constraint
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                fields=("leave_template", "leave_type", "category"),
                name="unique_leave_type_per_template_category",
            ),
        ),

        # Remove field safely
        migrations.RemoveField(
            model_name="leavetemplate",
            name="name",
        ),
    ]