# Generated by Django 6.0.3 on 2026-06-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0008_monthlyprogressreport_and_more"),
    ]

    operations = [
       
       
        migrations.AlterField(
            model_name="monthlyprogressreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
