# Generated by Django 6.0.3 on 2026-06-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_remove_leavetemplate_unique_staff_leave_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffremainingleave",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.leavetype",
            ),
        ),
    ]
