# Generated by Django 6.0.3 on 2026-06-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_remove_leavetemplate_unique_staff_leave_type_and_more"),
    ]

    operations = [
       
        migrations.AddField(
            model_name="monthlyprogressreport",
            name="overall_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        
    ]
