# Generated by Django 6.0.3 on 2026-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0009_announcement_expires_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="data",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="generated_by",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="is_auto_generated",
        ),
        migrations.RemoveField(
            model_name="certificatetype",
            name="template_file",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="CertificateFieldDefinition",
        ),
    ]
