# Generated by Django 6.0.3 on 2026-06-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_add__staffremainingleave_leave_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leavetemplate",
            name="unique_staff_leave_type",
        ),
    ]
