# Generated by Django 6.0.3 on 2026-06-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_remove_leavetemplate_unique_staff_leave_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="school",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="studentparent",
            name="parent",
        ),
       
        migrations.RemoveField(
            model_name="studentparent",
            name="student",
        ),
       
       
        migrations.DeleteModel(
            name="Parent",
        ),
        migrations.DeleteModel(
            name="StudentParent",
        ),
    ]
