# Generated by Django 6.0.3 on 2026-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0010_remove_certificate_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="issued_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="budgetexpense",
            name="description",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="lossprevention",
            name="remark",
            field=models.TextField(max_length=250),
        ),
    ]
