# Generated by Django 6.0.3 on 2026-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_remove_leavetemplate_unique_staff_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="If True, salary will be deducted for approved days of this leave request.",
            ),
        ),
    ]
