# Generated by Django 6.0.3 on 2026-06-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_remove_parent_school_remove_parent_user_and_more"),
    ]

    # operations = [
       
    #     migrations.AlterField(
    #         model_name="student",
    #         name="division",
    #         field=models.ForeignKey(
    #             blank=True,
    #             null=True,
    #             on_delete=django.db.models.deletion.SET_NULL,
    #             to="sms_app.division",
    #         ),
    #     ),
    # ]
