# Generated by Django 6.0.3 on 2026-07-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0011_rename_issued_at_certificate_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template",
                        to="sms_app.certificatetype",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_template",
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("date", "Date"),
                            ("number", "Number"),
                            ("textarea", "Textarea"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("editable", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_order", models.PositiveIntegerField(default=1)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="sms_app.certificatetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_template_field",
                "ordering": ["display_order"],
            },
        ),
    ]
