# Generated by Django 6.0.3 on 2026-06-11 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0012_leaverequest_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffremainingleave",
            name="remaining_leaves",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
