# Generated by Django 6.0.3 on 2026-06-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0013_alter_staffremainingleave_remaining_leaves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffremainingleave",
            name="remaining_leaves",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
