# Generated by Django 6.0.3 on 2026-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0013_homeworksubmissions_delete_homeworksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffremainingleave',
            name='month',
            field=models.IntegerField(default=8),
        ),
    ]
