# Generated by Django 6.0.3 on 2026-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0014_alter_staffremainingleave_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
