# Generated by Django 6.0.3 on 2026-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0014_alter_staffremainingleave_remaining_leaves"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_carry_forward",
            field=models.BooleanField(default=False),
        ),
    ]
