# Generated by Django 6.0.3 on 2026-06-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0007_exam_examnotification_staffface_studentdocument_and_more"),
        ("sms_app", "0015_leavetype_is_carry_forward"),
    ]

    operations = []
