# Generated by Django 6.0.3 on 2026-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0015_alter_student_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='is_bounced',
            field=models.BooleanField(default=False),
        ),
    ]
