# Generated by Django 6.0.3 on 2026-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0016_studentfeepayment_is_bounced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=20),
        ),
    ]
