# Generated by Django 6.0.3 on 2026-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0017_alter_studentfeepayment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='index_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
