# Generated by Django 6.0.3 on 2026-08-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0019_department_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='school_class',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
            ],
            options={
                'db_table': 'class_category',
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.classcategory'),
        ),
    ]
