# Generated by Django 6.0.3 on 2026-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0020_alter_schoolclass_school_class_classcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                blank=True, default="PENDING", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffremainingleave",
            name="month",
            field=models.IntegerField(default=10),
        ),
    ]
