# Generated by Django 6.0.3 on 2026-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0020_alter_schoolclass_school_class_classcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
