# Generated by Django 6.0.3 on 2026-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0020_alter_schoolclass_school_class_classcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        # leave_request.status already exists in the database (it was applied under the
        # previous migration name 0021_leaverequest_status_student_roll_no). Record the
        # field in migration state without re-issuing the ADD COLUMN, which would fail
        # with "column status of relation leave_request already exists".
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='leaverequest',
                    name='status',
                    field=models.CharField(blank=True, default='PENDING', max_length=20, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='staffremainingleave',
            name='month',
            field=models.IntegerField(default=10),
        ),
    ]
