# Generated by Django 6.0.3 on 2026-08-16 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0021_leaverequest_status_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWeightageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('EXAM', 'Examination'), ('ATTENDANCE', 'Attendance Percentage'), ('TEACHER_ASSESSMENT', 'Teacher Assessment'), ('CUSTOM', 'Custom Assessment / Project')], default='EXAM', max_length=30)),
                ('weightage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'result_weightage_component',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.DecimalField(decimal_places=2, default=33.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('SENT_BACK', 'Sent Back')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('building_block', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
            ],
            options={
                'db_table': 'exam_room',
                'unique_together': {('school', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.examroom'),
        ),
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33.0, max_digits=6)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
                ('weightage_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_terms', to='sms_app.resultweightagecomponent')),
            ],
            options={
                'db_table': 'exam_term',
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherMarksVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SENT_BACK', 'Sent Back')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.academicyear')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.schoolclass')),
                ('exam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.examterm')),
            ],
            options={
                'db_table': 'class_teacher_marks_verification',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='sms_app.examterm'),
        ),
        migrations.CreateModel(
            name='ResultAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'result_audit_log',
            },
        ),
        migrations.CreateModel(
            name='ResultWeightageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Academic Year Weightage Configuration', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightage_configs', to='sms_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
            ],
            options={
                'db_table': 'result_weightage_config',
                'unique_together': {('school', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='resultweightagecomponent',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sms_app.resultweightageconfig'),
        ),
        migrations.CreateModel(
            name='TeacherAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assessments', to='sms_app.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.staff')),
            ],
            options={
                'db_table': 'teacher_assessment_score',
            },
        ),
        migrations.CreateModel(
            name='FinalStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('component_breakdown', models.JSONField(default=dict)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('PROCESSING', 'Processing'), ('READY_FOR_REVIEW', 'Ready for Review'), ('SENT_BACK', 'Sent Back'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='NOT_READY', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='sms_app.student')),
            ],
            options={
                'db_table': 'final_student_result',
                'unique_together': {('academic_year', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SeatingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='sms_app.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_allocations', to='sms_app.student')),
            ],
            options={
                'db_table': 'seating_allocation',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
