# Generated by Django 6.0.3 on 2026-08-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0022_resultweightagecomponent_exam_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='is_rte_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_rte',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RTEDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='rte_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rte_documents', to='sms_app.student')),
            ],
            options={
                'db_table': 'rte_document',
            },
        ),
    ]
