# Generated by Django 6.0.3 on 2026-08-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0023_schoolclass_is_rte_applicable_student_is_rte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_rte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtedocument',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rte_documents', to='sms_app.admission'),
        ),
        migrations.AlterField(
            model_name='rtedocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rte_documents', to='sms_app.student'),
        ),
    ]
