# Generated by Django 6.0.3 on 2026-08-31 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0024_admission_is_rte_rtedocument_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(default='Board Room / Online', max_length=255)),
                ('attendees', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
            ],
            options={
                'db_table': 'board_meeting',
            },
        ),
        migrations.CreateModel(
            name='PostTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], default='INWARD', max_length=20)),
                ('post_name', models.CharField(max_length=255)),
                ('for_post', models.CharField(max_length=255)),
                ('to_post', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_tracking/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.school')),
            ],
            options={
                'db_table': 'post_tracking',
            },
        ),
    ]
