# Generated by Django 6.0.3 on 2026-08-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0025_boardmeeting_posttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmissions',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmissions',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.staff'),
        ),
        migrations.AddField(
            model_name='homeworksubmissions',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='homeworksubmissions',
            name='status',
            field=models.CharField(default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='homeworksubmissions',
            name='teacher_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworksubmissions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='homework_submissions/'),
        ),
    ]
