# Generated by Django 6.0.3 on 2026-09-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0026_homeworksubmissions_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='condition_on_return',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='damage_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='lost_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookissued',
            name='total_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookissued',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='ISSUED', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffremainingleave',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='sms_app.school')),
            ],
            options={
                'db_table': 'book_author',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sms_app.author'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='sms_app.school')),
            ],
            options={
                'db_table': 'book_category',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sms_app.bookcategory'),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('RESERVED', 'Reserved'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged'), ('UNDER_REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('MINOR_DAMAGE', 'Minor Damage'), ('MAJOR_DAMAGE', 'Major Damage')], default='GOOD', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='sms_app.book')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='sms_app.school')),
            ],
            options={
                'db_table': 'book_copy',
            },
        ),
        migrations.AddField(
            model_name='bookissued',
            name='book_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='sms_app.bookcopy'),
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('queue_number', models.PositiveIntegerField(default=1)),
                ('available_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('AVAILABLE', 'Available'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sms_app.book')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to='sms_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reservations', to='sms_app.student')),
            ],
            options={
                'db_table': 'book_reservation',
            },
        ),
        migrations.CreateModel(
            name='LibrarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_books_per_student', models.PositiveIntegerField(default=3)),
                ('issue_duration_days', models.PositiveIntegerField(default=14)),
                ('max_renewal_count', models.PositiveIntegerField(default=2)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('lost_penalty', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('damage_penalty', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('allow_renewal_with_fine', models.BooleanField(default=False)),
                ('allow_issue_with_fine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_settings', to='sms_app.school')),
            ],
            options={
                'db_table': 'library_settings',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publishers', to='sms_app.school')),
            ],
            options={
                'db_table': 'book_publisher',
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sms_app.publisher'),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_code', models.CharField(max_length=50)),
                ('rack_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_racks', to='sms_app.school')),
            ],
            options={
                'db_table': 'library_rack',
                'unique_together': {('school', 'rack_code')},
            },
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='sms_app.rack'),
        ),
        migrations.AddField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sms_app.rack'),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_code', models.CharField(max_length=50)),
                ('shelf_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='sms_app.rack')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_shelves', to='sms_app.school')),
            ],
            options={
                'db_table': 'library_shelf',
                'unique_together': {('rack', 'shelf_code')},
            },
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='sms_app.shelf'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sms_app.shelf'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcopy',
            unique_together={('school', 'accession_no')},
        ),
    ]
