# Generated by Django 6.0.3 on 2026-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0028_inventorybundle_inventorycategory_inventorybudget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='android_package_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='app_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ios_bundle_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(blank=True, default='#4F46E5', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
