# Generated by Django 6.0.3 on 2026-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0029_school_android_package_id_school_app_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='android_package_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='ios_bundle_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
