# Generated by Django 6.0.3 on 2026-09-02 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0030_school_android_package_name_school_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='android_package_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='android_package_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='app_display_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='school',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='school',
            name='domain_verified',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ios_bundle_id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='school',
            name='subdomain',
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('TRIAL', 'Free Trial'), ('PAID', 'Paid Subscription')], default='TRIAL', max_length=20)),
                ('billing_model', models.CharField(choices=[('FLAT', 'Flat Fixed Rate'), ('PER_STUDENT', 'Per-Student Dynamic Billing')], default='FLAT', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_student_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('TRIAL', 'Active Trial'), ('ACTIVE', 'Active Subscription'), ('EXPIRED', 'Expired / Overdue'), ('SUSPENDED', 'Locked / Suspended')], default='TRIAL', max_length=20)),
                ('auto_lock_on_due', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='sms_app.school')),
            ],
            options={
                'db_table': 'school_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SchoolInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_model', models.CharField(default='FLAT', max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online / Razorpay / UPI'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='ONLINE', max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sms_app.school')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sms_app.schoolsubscription')),
            ],
            options={
                'db_table': 'school_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
