# Generated by Django 6.0.3 on 2026-09-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0031_remove_school_android_package_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pricing_model', models.CharField(choices=[('PER_STUDENT', 'Per-Student Dynamic Billing'), ('FLAT', 'Flat Fixed Rate')], default='PER_STUDENT', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('half_yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('trial_available', models.BooleanField(default=True)),
                ('trial_duration_days', models.PositiveIntegerField(default=14)),
                ('max_students', models.PositiveIntegerField(default=500, help_text='0 for unlimited')),
                ('max_teachers', models.PositiveIntegerField(default=50, help_text='0 for unlimited')),
                ('max_staff', models.PositiveIntegerField(default=50, help_text='0 for unlimited')),
                ('max_admin_users', models.PositiveIntegerField(default=5, help_text='0 for unlimited')),
                ('storage_limit_mb', models.PositiveIntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_settings',
            },
        ),
        migrations.AddField(
            model_name='schoolinvoice',
            name='billing_cycle',
            field=models.CharField(default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolinvoice',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='student_count_at_purchase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', '6 Months'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Active Trial'), ('TRIAL_EXPIRED', 'Trial Expired'), ('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active Subscription'), ('EXPIRING', 'Expiring Soon'), ('EXPIRED', 'Expired / Overdue'), ('GRACE_PERIOD', 'Grace Period'), ('SUSPENDED', 'Locked / Suspended'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=25),
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_audit_logs', to='sms_app.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=150, null=True)),
                ('gateway', models.CharField(default='RAZORPAY', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('payment_method', models.CharField(default='ONLINE', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sms_app.schoolinvoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='sms_app.school')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sms_app.schoolsubscription')),
            ],
            options={
                'db_table': 'subscription_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_subscriptions', to='sms_app.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='sms_app.module')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='sms_app.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_plan_modules',
                'unique_together': {('plan', 'module')},
            },
        ),
    ]
