# Generated by Django 6.0.3 on 2026-10-05 07:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0032_subscriptionplan_subscriptionsetting_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DROP TABLE IF EXISTS inventory_purchase_item CASCADE;
                    DROP TABLE IF EXISTS inventory_purchase CASCADE;
                    DROP TABLE IF EXISTS inventory_supplier CASCADE;
                    DROP TABLE IF EXISTS inventory_stock_adjustment_item CASCADE;
                    DROP TABLE IF EXISTS inventory_stock_adjustment CASCADE;
                    DROP TABLE IF EXISTS inventory_stock_transaction CASCADE;
                    DROP TABLE IF EXISTS inventory_student_item_issue_item CASCADE;
                    DROP TABLE IF EXISTS inventory_student_item_issue CASCADE;
                    DROP TABLE IF EXISTS inventory_student_item_entitlement CASCADE;
                    DROP TABLE IF EXISTS inventory_item_pricing CASCADE;
                    DROP TABLE IF EXISTS inventory_item_size CASCADE;
                    DROP TABLE IF EXISTS inventory_item_color CASCADE;
                    DROP TABLE IF EXISTS inventory_item CASCADE;
                    DROP TABLE IF EXISTS inventory_item_category CASCADE;
                    DROP TABLE IF EXISTS inventory_audit_log CASCADE;
                    DROP TABLE IF EXISTS inventory_bundle_item CASCADE;
                    DROP TABLE IF EXISTS inventory_bundle CASCADE;
                    DROP TABLE IF EXISTS inventory_return_item CASCADE;
                    DROP TABLE IF EXISTS inventory_return CASCADE;
                    DROP TABLE IF EXISTS inventory_stock_balance CASCADE;
                    DROP TABLE IF EXISTS inventory_opening_stock CASCADE;
                    DROP TABLE IF EXISTS inventory_warehouse CASCADE;
                    DROP TABLE IF EXISTS inventory_unit CASCADE;
                    DROP TABLE IF EXISTS inventory_subcategory CASCADE;
                    DROP TABLE IF EXISTS inventory_category CASCADE;
                    DROP TABLE IF EXISTS inventory_budget CASCADE;
                    DROP TABLE IF EXISTS student_id_card CASCADE;
                    """,
                    reverse_sql=""
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(name='inventorybundle', unique_together=None),
                migrations.AlterUniqueTogether(name='inventorycategory', unique_together=None),
                migrations.AlterUniqueTogether(name='inventoryitem', unique_together=None),
                migrations.AlterUniqueTogether(name='inventoryitemvariant', unique_together=None),
                migrations.AlterUniqueTogether(name='inventorystockbalance', unique_together=None),
                migrations.AlterUniqueTogether(name='inventorysubcategory', unique_together=None),
                migrations.AlterUniqueTogether(name='inventoryunit', unique_together=None),
                migrations.AlterUniqueTogether(name='inventorywarehouse', unique_together=None),
                migrations.RemoveField(model_name='inventorybundle', name='applicable_class'),
                migrations.RemoveField(model_name='inventorybundle', name='school'),
                migrations.RemoveField(model_name='inventorybundleitem', name='bundle'),
                migrations.RemoveField(model_name='inventorybundleitem', name='item'),
                migrations.RemoveField(model_name='inventorybundleitem', name='variant'),
                migrations.RemoveField(model_name='inventorycategory', name='school'),
                migrations.RemoveField(model_name='inventorysubcategory', name='category'),
                migrations.RemoveField(model_name='inventoryitem', name='category'),
                migrations.RemoveField(model_name='inventoryitem', name='school'),
                migrations.RemoveField(model_name='inventoryitem', name='sub_category'),
                migrations.RemoveField(model_name='inventorytransaction', name='item'),
                migrations.RemoveField(model_name='inventoryopeningstock', name='item'),
                migrations.RemoveField(model_name='inventoryitemvariant', name='item'),
                migrations.RemoveField(model_name='studentinventoryissueitem', name='item'),
                migrations.RemoveField(model_name='inventorystockadjustmentitem', name='item'),
                migrations.RemoveField(model_name='purchaserequestitem', name='item'),
                migrations.RemoveField(model_name='inventorypurchaseitem', name='item'),
                migrations.RemoveField(model_name='inventoryreturnitem', name='item'),
                migrations.RemoveField(model_name='inventorystockbalance', name='item'),
                migrations.RemoveField(model_name='inventoryitemvariant', name='applicable_class'),
                migrations.RemoveField(model_name='purchaserequestitem', name='variant'),
                migrations.RemoveField(model_name='inventorypurchaseitem', name='variant'),
                migrations.RemoveField(model_name='inventorystockadjustmentitem', name='variant'),
                migrations.RemoveField(model_name='inventoryreturnitem', name='variant'),
                migrations.RemoveField(model_name='inventorystockbalance', name='variant'),
                migrations.RemoveField(model_name='inventorytransaction', name='variant'),
                migrations.RemoveField(model_name='inventoryopeningstock', name='variant'),
                migrations.RemoveField(model_name='studentinventoryissueitem', name='variant'),
                migrations.RemoveField(model_name='inventoryopeningstock', name='created_by'),
                migrations.RemoveField(model_name='inventoryopeningstock', name='school'),
                migrations.RemoveField(model_name='inventoryopeningstock', name='warehouse'),
                migrations.RemoveField(model_name='inventorypurchase', name='created_by'),
                migrations.RemoveField(model_name='inventorypurchase', name='school'),
                migrations.RemoveField(model_name='inventorypurchase', name='supplier'),
                migrations.RemoveField(model_name='inventorypurchase', name='warehouse'),
                migrations.RemoveField(model_name='inventorypurchaseitem', name='purchase'),
                migrations.RemoveField(model_name='inventoryreturn', name='received_by'),
                migrations.RemoveField(model_name='inventoryreturn', name='school'),
                migrations.RemoveField(model_name='inventoryreturn', name='staff'),
                migrations.RemoveField(model_name='inventoryreturn', name='student'),
                migrations.RemoveField(model_name='inventoryreturn', name='warehouse'),
                migrations.RemoveField(model_name='inventoryreturnitem', name='inventory_return'),
                migrations.RemoveField(model_name='inventorystockadjustment', name='approved_by'),
                migrations.RemoveField(model_name='inventorystockadjustment', name='created_by'),
                migrations.RemoveField(model_name='inventorystockadjustment', name='school'),
                migrations.RemoveField(model_name='inventorystockadjustment', name='warehouse'),
                migrations.RemoveField(model_name='inventorystockadjustmentitem', name='adjustment'),
                migrations.RemoveField(model_name='inventorystockbalance', name='last_transaction'),
                migrations.RemoveField(model_name='inventorystockbalance', name='school'),
                migrations.RemoveField(model_name='inventorystockbalance', name='warehouse'),
                migrations.RemoveField(model_name='inventorysubcategory', name='school'),
                migrations.RemoveField(model_name='inventorysupplier', name='school'),
                migrations.RemoveField(model_name='inventorytransaction', name='created_by'),
                migrations.RemoveField(model_name='inventorytransaction', name='school'),
                migrations.RemoveField(model_name='inventorytransaction', name='to_warehouse'),
                migrations.RemoveField(model_name='inventorytransaction', name='warehouse'),
                migrations.RemoveField(model_name='inventoryunit', name='school'),
                migrations.RemoveField(model_name='inventorywarehouse', name='incharge_user'),
                migrations.RemoveField(model_name='inventorywarehouse', name='school'),
                migrations.RemoveField(model_name='studentinventoryissue', name='warehouse'),
                migrations.RemoveField(model_name='purchaserequest', name='requested_by'),
                migrations.RemoveField(model_name='purchaserequest', name='school'),
                migrations.RemoveField(model_name='purchaserequestitem', name='purchase_request'),
                migrations.RemoveField(model_name='studentidcard', name='issued_by'),
                migrations.RemoveField(model_name='studentidcard', name='previous_card'),
                migrations.RemoveField(model_name='studentidcard', name='school'),
                migrations.RemoveField(model_name='studentidcard', name='student'),
                migrations.RemoveField(model_name='studentinventoryissue', name='academic_year'),
                migrations.RemoveField(model_name='studentinventoryissue', name='issued_by'),
                migrations.RemoveField(model_name='studentinventoryissue', name='school'),
                migrations.RemoveField(model_name='studentinventoryissue', name='student'),
                migrations.RemoveField(model_name='studentinventoryissueitem', name='student_issue'),
                migrations.DeleteModel(name='InventoryBudget'),
                migrations.DeleteModel(name='InventoryBundle'),
                migrations.DeleteModel(name='InventoryBundleItem'),
                migrations.DeleteModel(name='InventoryCategory'),
                migrations.DeleteModel(name='InventoryItem'),
                migrations.DeleteModel(name='InventoryItemVariant'),
                migrations.DeleteModel(name='InventoryOpeningStock'),
                migrations.DeleteModel(name='InventoryPurchase'),
                migrations.DeleteModel(name='InventoryPurchaseItem'),
                migrations.DeleteModel(name='InventoryReturn'),
                migrations.DeleteModel(name='InventoryReturnItem'),
                migrations.DeleteModel(name='InventoryStockAdjustment'),
                migrations.DeleteModel(name='InventoryStockAdjustmentItem'),
                migrations.DeleteModel(name='InventoryStockBalance'),
                migrations.DeleteModel(name='InventorySubCategory'),
                migrations.DeleteModel(name='InventorySupplier'),
                migrations.DeleteModel(name='InventoryTransaction'),
                migrations.DeleteModel(name='InventoryUnit'),
                migrations.DeleteModel(name='InventoryWarehouse'),
                migrations.DeleteModel(name='PurchaseRequest'),
                migrations.DeleteModel(name='PurchaseRequestItem'),
                migrations.DeleteModel(name='StudentIDCard'),
                migrations.DeleteModel(name='StudentInventoryIssue'),
                migrations.DeleteModel(name='StudentInventoryIssueItem'),
            ]
        ),
        migrations.AlterField(
            model_name='staffremainingleave',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audit_logs', to='sms_app.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='sms_app.school')),
            ],
            options={
                'db_table': 'inventory_item_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='Pcs', max_length=50)),
                ('has_size', models.BooleanField(default=False)),
                ('has_color', models.BooleanField(default=False)),
                ('is_returnable', models.BooleanField(default=False)),
                ('minimum_stock_level', models.IntegerField(default=5)),
                ('maximum_stock_level', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='sms_app.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sms_app.itemcategory')),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_colors', to='sms_app.school')),
            ],
            options={
                'db_table': 'inventory_item_color',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('charging_type', models.CharField(choices=[('INCLUDED_IN_FEE', 'Included In Fee'), ('SEPARATE_CHARGE', 'Separate Charge'), ('FREE', 'Free')], default='SEPARATE_CHARGE', max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_pricings', to='sms_app.academicyear')),
                ('included_fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_inventory_items', to='sms_app.feetype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='sms_app.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_pricings', to='sms_app.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_pricings', to='sms_app.schoolclass')),
            ],
            options={
                'db_table': 'inventory_item_pricing',
                'ordering': ['-academic_year__id', 'item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_type', models.CharField(blank=True, default='General', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sizes', to='sms_app.school')),
            ],
            options={
                'db_table': 'inventory_item_size',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_suppliers', to='sms_app.school')),
            ],
            options={
                'db_table': 'inventory_supplier',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_purchases', to='sms_app.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_purchases', to='sms_app.school')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='sms_app.supplier')),
            ],
            options={
                'db_table': 'inventory_purchase',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='sms_app.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sms_app.purchase')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
            ],
            options={
                'db_table': 'inventory_purchase_item',
            },
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('WRONG_SIZE', 'Wrong Size'), ('DEFECTIVE', 'Defective'), ('WORN_OUT', 'Worn Out'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='sms_app.academicyear')),
                ('current_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_replacement_requests', to='sms_app.itemcolor')),
                ('current_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_replacement_requests', to='sms_app.itemsize')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='sms_app.item')),
                ('requested_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_replacement_requests', to='sms_app.itemcolor')),
                ('requested_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_replacement_requests', to='sms_app.itemsize')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_replacements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='sms_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='sms_app.student')),
            ],
            options={
                'db_table': 'inventory_replacement_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADJUSTMENT_IN', 'Adjustment In (+)'), ('ADJUSTMENT_OUT', 'Adjustment Out (-)'), ('DAMAGE', 'Damage (-)'), ('LOST', 'Lost (-)')], max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('adjustment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='sms_app.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='sms_app.school')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment',
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('ISSUE', 'Student Issue'), ('RETURN', 'Student Return'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('DAMAGE', 'Damaged Stock'), ('LOST', 'Lost Stock')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('unit_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sms_app.academicyear')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sms_app.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sms_app.school')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
            ],
            options={
                'db_table': 'inventory_stock_transaction',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentItemEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitled_quantity', models.IntegerField(default=1)),
                ('issued_quantity', models.IntegerField(default=0)),
                ('charging_type', models.CharField(choices=[('INCLUDED_IN_FEE', 'Included In Fee'), ('SEPARATE_CHARGE', 'Separate Charge'), ('FREE', 'Free')], default='INCLUDED_IN_FEE', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('FULLY_ISSUED', 'Fully Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entitlements', to='sms_app.academicyear')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('fee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.feetype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entitlements', to='sms_app.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entitlements', to='sms_app.school')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_entitlements', to='sms_app.student')),
            ],
            options={
                'db_table': 'inventory_student_entitlement',
                'ordering': ['student__surname', 'item__item_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentItemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('charging_type', models.CharField(choices=[('INCLUDED_IN_FEE', 'Included In Fee'), ('SEPARATE_CHARGE', 'Separate Charge'), ('FREE', 'Free')], default='SEPARATE_CHARGE', max_length=30)),
                ('charged_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_reason', models.CharField(choices=[('INITIAL_ISSUE', 'Initial Issue'), ('REPLACEMENT', 'Replacement'), ('ADDITIONAL', 'Additional'), ('SPECIAL_CASE', 'Special Case'), ('OTHER', 'Other')], default='INITIAL_ISSUE', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_item_issues', to='sms_app.academicyear')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_issues', to='sms_app.item')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_item_issues', to='sms_app.school')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_issues', to='sms_app.student')),
            ],
            options={
                'db_table': 'inventory_student_issue',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('GOOD', 'Good (Restockable)'), ('DAMAGED', 'Damaged'), ('UNUSABLE', 'Unusable')], default='GOOD', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemcolor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_returns', to='sms_app.item')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_item_returns', to='sms_app.school')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms_app.itemsize')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_returns', to='sms_app.student')),
            ],
            options={
                'db_table': 'inventory_student_return',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_item_category'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('school', 'item_code'), name='unique_school_item_code'),
        ),
        migrations.AddConstraint(
            model_name='itemcolor',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_color'),
        ),
        migrations.AddConstraint(
            model_name='itemsize',
            constraint=models.UniqueConstraint(fields=('school', 'name', 'size_type'), name='unique_school_size_variant'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['school', 'item'], name='inventory_s_school__0f63df_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['school', 'transaction_date'], name='inventory_s_school__f3423e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_s_transac_78fb87_idx'),
        ),
    ]
