# Generated by Django 6.0.3 on 2026-10-06 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0033_merge_local_ui_and_incoming_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('admission', 'Admission'), ('student', 'Student record'), ('rte', 'RTE')], max_length=20)),
                ('document_id', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('requires_reupload', 'Requires reupload')], default='pending', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reviews', to='sms_app.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'source', 'document_id'), name='unique_student_document_review')],
            },
        ),
    ]
