# Generated by Django 6.0.3 on 2026-10-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0033_alter_inventorybundle_unique_together_and_more'),
        ('sms_app', '0033_merge_local_ui_and_incoming_features'),
    ]

    operations = [
    ]
