# Generated by Django 6.0.3 on 2026-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0034_merge_20261006_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='is_rte_applicable',
            field=models.BooleanField(default=False, help_text='If True/Yes, RTE students pay normally. If False/No, RTE students pay ₹0 and the fee is claimed from Government.'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='is_rte_govt_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='rte_govt_claim_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='rte_govt_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='rte_govt_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending Claim'), ('partially_received', 'Partially Received'), ('received', 'Received')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='payer_type',
            field=models.CharField(choices=[('student', 'Student / Parent'), ('government', 'Government RTE Claim')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('govt_rte', 'Government RTE Reimbursement')], max_length=20),
        ),
    ]
