# Generated by Django 6.0.3 on 2026-10-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0035_document_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ID', 'Government ID'), ('DOCUMENT', 'Document')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_fields', to='sms_app.school')),
            ],
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='profile_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sms_app.schoolprofilefield'),
        ),
        migrations.CreateModel(
            name='StudentProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.schoolprofilefield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_values', to='sms_app.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schoolprofilefield',
            constraint=models.UniqueConstraint(fields=('school', 'kind', 'key'), name='unique_school_profile_field'),
        ),
        migrations.AddConstraint(
            model_name='studentprofilevalue',
            constraint=models.UniqueConstraint(fields=('student', 'field'), name='unique_student_profile_value'),
        ),
    ]
