# Generated by Django 6.0.3 on 2026-05-08 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0036_staffsalarypayment_calculation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorPayData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_key_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sms_app.school"
                    ),
                ),
            ],
        ),
    ]
