# Generated by Django 6.0.3 on 2026-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0037_razorpaydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="pay_process",
            field=models.BooleanField(default=False),
        ),
    ]
