# Generated by Django 6.0.3 on 2026-10-07 12:15

import sms_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0037_merge_fee_and_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="max_consecutive_periods",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_daily_periods",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_weekly_periods",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="syllabus_file",
            field=models.FileField(
                storage=sms_app.storage.get_raw_document_storage, upload_to="syllabus/"
            ),
        ),
    ]
