# Generated by Django 6.0.3 on 2026-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0038_staff_max_consecutive_periods_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="max_daily_periods",
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_fri",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_mon",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_sat",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_thu",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_tue",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="staff",
            name="max_periods_wed",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
