# Generated by Django 6.0.3 on 2026-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0038_admission_pay_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
