# Generated by Django 6.0.3 on 2026-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0039_student_aadhar_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExtraData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "scheduled_caste",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("leaving_date", models.DateField(blank=True, null=True)),
                (
                    "last_school",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("progress", models.TextField(blank=True, null=True)),
                ("conduct", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
