# Generated by Django 6.0.3 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sms_app",
            "0039_remove_staff_max_daily_periods_staff_max_periods_fri_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
