# Generated by Django 6.0.3 on 2026-05-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0040_studentextradata"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentextradata",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.student",
            ),
        ),
    ]
