# Generated by Django 6.0.3 on 2026-10-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0040_alter_staff_joining_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="leavetemplate",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allocation_count",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allocation_period",
            field=models.CharField(
                choices=[
                    ("Monthly", "Monthly"),
                    ("Quarterly", "Quarterly"),
                    ("Yearly", "Yearly"),
                ],
                default="Yearly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_encashment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="carry_forward",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="max_carry_forward",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="calc_base",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="calc_type",
            field=models.CharField(
                choices=[
                    ("Fixed", "Fixed"),
                    ("Percentage", "Percentage"),
                    ("Formula", "Formula"),
                ],
                default="Fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="type",
            field=models.CharField(
                choices=[("Earning", "Earning"), ("Deduction", "Deduction")],
                default="Earning",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="staff",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="exit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="leave_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="sms_app.leavetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.schoolfeature",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="leave_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_types",
                to="sms_app.leavetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="leave_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="component_type",
            field=models.CharField(
                choices=[("earning", "Earning"), ("deduction", "Deduction")],
                default="earning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarycomponent",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_components",
                to="sms_app.school",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRegularization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("requested_check_in", models.TimeField(blank=True, null=True)),
                ("requested_check_out", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("audit_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_regularizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_regularizations",
                        to="sms_app.staff",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_regularization",
                "ordering": ["-attendance_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Shift", max_length=100)),
                ("check_in_time", models.TimeField()),
                ("check_out_time", models.TimeField()),
                ("grace_period_mins", models.PositiveIntegerField(default=15)),
                ("half_day_threshold_mins", models.PositiveIntegerField(default=120)),
                ("geo_required", models.BooleanField(default=True)),
                (
                    "geo_radius_meters",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_settings",
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_setting",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="attendance_setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="sms_app.attendancesetting",
            ),
        ),
        migrations.CreateModel(
            name="LeaveCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_cycles",
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "leave_cycle",
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary_month", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Generated", "Generated"),
                            ("Approved", "Approved"),
                            ("Locked", "Locked"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("total_processed", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_runs",
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_run",
                "unique_together": {("school", "salary_month")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True,
                        related_name="salary_structures",
                        to="sms_app.salarycomponent",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structures",
                        to="sms_app.school",
                    ),
                ),
            ],
            options={
                "db_table": "salary_structure",
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="salary_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="sms_app.salarystructure",
            ),
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "carry_forward",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "pending",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="sms_app.leavetype",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="sms_app.staff",
                    ),
                ),
                (
                    "leave_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="sms_app.leavecycle",
                    ),
                ),
            ],
            options={
                "db_table": "leave_balance",
                "unique_together": {("staff", "leave_type", "leave_cycle")},
            },
        ),
        migrations.CreateModel(
            name="PayrollPayslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "present_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "paid_leaves",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "unpaid_leaves",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "gross_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("component_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="sms_app.staff",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="sms_app.payrollrun",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslip",
                "unique_together": {("staff", "payroll_run")},
            },
        ),
    ]
