# Generated by Django 6.0.3 on 2026-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0041_studentextradata_student"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "gr_no"), name="unique_school_gr_no"
            ),
        ),
    ]
