# Generated by Django 6.0.3 on 2026-10-08 10:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0041_leavetemplate_is_active_leavetemplate_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_early_exit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
