# Generated by Django 6.0.3 on 2026-10-08 10:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0042_attendance_is_early_exit_attendance_is_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="dynamic_leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dynamic_leave_requests",
                to="sms_app.leavetype",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="is_paid",
            field=models.BooleanField(
                default=True,
                help_text="If True, paid leave (no deduction). If False, unpaid/LOP (salary deducted).",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="total_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=Decimal("1.0"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
