# Generated by Django 6.0.3 on 2026-05-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0042_student_unique_school_gr_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
