# Generated by Django 6.0.3 on 2026-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0043_leaverequest_dynamic_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='gst_included',
            field=models.BooleanField(default=False, help_text='Whether GST is applied to this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
