# Generated by Django 6.0.3 on 2026-10-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0044_subscriptionplan_gst_included_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultweightageconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultweightageconfig',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weightage_configs', to='sms_app.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='resultweightageconfig',
            unique_together={('school', 'academic_year', 'school_class')},
        ),
    ]
