# Generated by Django 6.0.3 on 2026-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0045_alter_resultweightageconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="correction_log",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="attendance",
                    name="source",
                    field=models.CharField(
                        blank=True, default="Punch", max_length=50, null=True
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
