# Generated by Django 6.0.3 on 2026-10-10 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0045_alter_resultweightageconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_for',
            field=models.CharField(blank=True, choices=[('ALL', 'All Users'), ('TEACHER', 'Teacher'), ('CLERK', 'Clerk'), ('FEE-MANAGER', 'Fee-manager'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TRANSPORT', 'Transport')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
