# Generated by Django 6.0.3 on 2026-05-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0046_timetable_lectureslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_number", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_slots",
                        to="sms_app.timetable",
                    ),
                ),
            ],
            options={
                "ordering": ["break_number"],
                "unique_together": {("timetable", "break_number")},
            },
        ),
    ]
