# Generated by Django 6.0.3 on 2026-10-10 05:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0046_attendance_correction_log_attendance_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesetting",
            name="biometric_required",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BiometricVerificationProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "purpose",
                    models.CharField(default="ATTENDANCE_PUNCH", max_length=50),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_proofs",
                        to="sms_app.school",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_proofs",
                        to="sms_app.staff",
                    ),
                ),
            ],
            options={
                "db_table": "biometric_verification_proof",
                "indexes": [
                    models.Index(
                        fields=["staff", "is_used", "expires_at"],
                        name="bio_proof_staff_idx",
                    )
                ],
            },
        ),
    ]
