# Generated by Django 6.0.3 on 2026-10-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0046_announcement_created_by_announcement_created_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_announcements', to='sms_app.schoolclass'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to='sms_app.student'),
        ),
    ]
