# Generated by Django 6.0.3 on 2026-10-10 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0047_announcement_target_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='holiday',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='event_type',
            field=models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EVENT', 'School Event'), ('EXAM', 'Exam / Assessment'), ('MEETING', 'Meeting / PTM'), ('CELEBRATION', 'Celebration / Activity'), ('OTHER', 'Other')], default='HOLIDAY', max_length=50),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_holiday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='target_audience',
            field=models.CharField(default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='holiday',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
