# Generated by Django 6.0.3 on 2026-10-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0047_announcement_target_class_and_more"),
        ("sms_app", "0047_attendancesetting_biometric_required_and_more"),
    ]

    operations = []
