# Generated by Django 6.0.3 on 2026-10-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0048_alter_holiday_options_attendance_source_and_more'),
        ('sms_app', '0048_merge_20261010_1240'),
    ]

    operations = [
    ]
