# Generated by Django 6.0.3 on 2026-05-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0048_timetableentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakslot",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.AddField(
            model_name="lectureslot",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms_app.school",
            ),
        ),
    ]
