# Generated by Django 6.0.3 on 2026-10-10 08:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0048_merge_20261010_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="leavecycle",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavecycle",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_leave_cycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leavecycle",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaveperday",
            name="day_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.0"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="leaveperday",
            name="session",
            field=models.CharField(default="FULL_DAY", max_length=20),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="audit_log",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_action_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_action_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_actioned_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("REQUESTED", "Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="half_day_session",
            field=models.CharField(
                choices=[
                    ("FULL_DAY", "Full Day"),
                    ("FIRST_HALF", "First Half"),
                    ("SECOND_HALF", "Second Half"),
                ],
                default="FULL_DAY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavetemplate",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_backdated_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_future_leave",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_negative_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="half_day_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="include_holidays",
            field=models.BooleanField(
                default=False, help_text="If True, holidays count towards leave"
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="include_weekends",
            field=models.BooleanField(
                default=False, help_text="If True, weekends count towards leave"
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="max_backdated_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="max_consecutive_days",
            field=models.PositiveIntegerField(default=0, help_text="0 means unlimited"),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="prorata_on_joining",
            field=models.CharField(
                choices=[("PRO_RATA", "Pro-Rata"), ("FULL", "Full"), ("NONE", "None")],
                default="PRO_RATA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening Balance"),
                            ("ALLOCATION", "Allocation"),
                            ("RESERVATION", "Pending Reservation"),
                            ("RELEASE", "Reservation Release"),
                            ("USAGE", "Approved Usage"),
                            ("CANCELLATION", "Cancellation Refund"),
                            ("CARRY_FORWARD", "Carry Forward Credit"),
                            ("EXPIRY", "Balance Expiry"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=6
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leave_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_transactions",
                        to="sms_app.leavecycle",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="sms_app.leaverequest",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_transactions",
                        to="sms_app.leavetype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_transactions",
                        to="sms_app.school",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_transactions",
                        to="sms_app.staff",
                    ),
                ),
            ],
            options={
                "db_table": "leave_transaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
