# Generated by Django 6.0.3 on 2026-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0049_breakslot_school_lectureslot_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffsalarycomponent",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
