# Generated by Django 6.0.3 on 2026-10-10 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0049_merge_20261010_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(choices=[('AUTH', 'Authentication & Security'), ('ACADEMICS', 'Academics & Curriculum'), ('ADMISSIONS', 'Admissions & Students'), ('FEES', 'Finance & Fees'), ('ATTENDANCE', 'Attendance Desk'), ('EXAMS', 'Exams & Results'), ('ANNOUNCEMENTS', 'Announcements'), ('EVENTS', 'Events & Holidays'), ('HR_LEAVES', 'HR & Leaves'), ('LIBRARY', 'Library Management'), ('INVENTORY', 'Stock & Inventory'), ('SETTINGS', 'System Settings'), ('OTHER', 'General / Other')], default='OTHER', max_length=50)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('PUBLISH', 'Result / Notice Published'), ('PAYMENT', 'Fee / Payment Processed'), ('ATTENDANCE_MARK', 'Attendance Marked'), ('LEAVE_APPROVE', 'Leave Approved'), ('LEAVE_REJECT', 'Leave Rejected'), ('EXPORT', 'Data Exported'), ('OTHER', 'Other Action')], default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='sms_app.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='activity_lo_school__70e223_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_f9dfaa_idx'), models.Index(fields=['module', '-created_at'], name='activity_lo_module_faac2d_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_61fa17_idx')],
            },
        ),
    ]
