# Generated by Django 6.0.3 on 2026-10-10 11:27

import django.db.models.deletion
import sms_app.support_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0050_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, default=sms_app.support_models.generate_ticket_number, max_length=64, unique=True)),
                ('requester_role', models.CharField(default='STAFF', max_length=64)),
                ('requester_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('TECHNICAL', 'Technical Issue / Bug'), ('FEES', 'Fees & Finance'), ('INVENTORY', 'Inventory & Assets'), ('ACADEMIC', 'Academic & Exams'), ('ACCOUNT', 'Account & Access')], default='GENERAL', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Waiting for Super Admin)'), ('IN_PROGRESS', 'In Progress (Chat Open)'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='sms_app.school')),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(default='USER', max_length=64)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('MEDIA', 'Media Attachment'), ('SYSTEM', 'System Notification')], default='TEXT', max_length=16)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='support_attachments/%Y/%m/%d/')),
                ('media_name', models.CharField(blank=True, max_length=255, null=True)),
                ('media_size_bytes', models.PositiveIntegerField(default=0)),
                ('media_content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms_app.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='support_tic_status_a78228_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_by', 'status'], name='support_tic_created_bb2aee_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['school', '-created_at'], name='support_tic_school__eda0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__e3cc1d_idx'),
        ),
    ]
