# Generated by Django 6.0.3 on 2026-05-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0051_daytimeline"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DayTimeLine",
            new_name="Time_Table_tb",
        ),
    ]
