# Generated by Django 6.0.3 on 2026-10-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0051_supportticket_ticketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLERK', 'Clerk'), ('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('TRUSTEE', 'Trustee'), ('FEES', 'Fees Management'), ('INVENTORY', 'Inventory'), ('GLOBAL', 'Global / All Roles')], db_index=True, max_length=30)),
                ('route_path', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(blank=True, default=list, help_text="List of steps: [{'step': 1, 'title': '...', 'description': '...', 'dummy_example': '...'}]")),
                ('dummy_data', models.JSONField(blank=True, default=list, help_text="List of dummy data/fields: [{'field': '...', 'sample_value': '...', 'instructions': '...'}]")),
                ('video_url', models.CharField(blank=True, default='', help_text='Optional YouTube / Vimeo / Drive URL', max_length=500)),
                ('tips', models.JSONField(blank=True, default=list, help_text="List of helpful tips: ['Tip 1', 'Tip 2']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_tutorial',
                'ordering': ['role', 'route_path'],
                'unique_together': {('role', 'route_path')},
            },
        ),
    ]
