# Generated by Django 6.0.3 on 2026-05-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0052_rename_daytimeline_time_table_tb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_lecture", models.BooleanField(default=False)),
                ("is_break", models.BooleanField(default=False)),
                ("lecture_number", models.PositiveIntegerField()),
                ("slot_start_time", models.TimeField(blank=True, null=True)),
                ("slot_end_time", models.TimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.staff",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms_app.time_table_tb",
                    ),
                ),
            ],
            options={
                "ordering": ["lecture_number"],
                "unique_together": {("timetable", "lecture_number")},
            },
        ),
    ]
