# Generated by Django 6.0.3 on 2026-10-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0049_leavebalance_opening_balance_leavecycle_closed_at_and_more"),
        ("sms_app", "0052_pagetutorial"),
    ]

    operations = []
