# Generated by Django 6.0.3 on 2026-05-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0053_slot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slot",
            options={"ordering": ["slot_number"]},
        ),
        migrations.RenameField(
            model_name="slot",
            old_name="lecture_number",
            new_name="slot_number",
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("timetable", "slot_number")},
        ),
    ]
