# Generated by Django 6.0.3 on 2026-05-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0055_studentattendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="homework/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="time_table_tb",
            name="unique_division_day",
        ),
        migrations.AlterField(
            model_name="slot",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="sms_app.time_table_tb",
            ),
        ),
        migrations.AddConstraint(
            model_name="time_table_tb",
            constraint=models.UniqueConstraint(
                fields=("school", "class_division", "day"), name="unique_division_day"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="sms_app.division",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="sms_app.school",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_homeworks",
                to="sms_app.staff",
            ),
        ),
    ]
