# Generated by Django 6.0.3 on 2026-05-20 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_app", "0059_academic_year_master_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionform",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sms_app.academicyear",
            ),
        ),
    ]
