from django.contrib import admin
from django.contrib.auth.models import User
from .models import *
admin.site.register(User)
admin.site.register(LeaveTemplate)
admin.site.register(LeaveRequest)
admin.site.register(LeavePerDay)
admin.site.register(StaffRemainingLeave)
admin.site.register(Staff)
admin.site.register(School)
admin.site.register(CustomUser)
admin.site.register(Attendance)
admin.site.register(StaffFace)
admin.site.register(AttendanceLocation)
admin.site.register(Parent)
admin.site.register(Student)
admin.site.register(StudentParent)
admin.site.register(StudentDocument)
admin.site.register(SchoolClass)
admin.site.register(StudentNotification)
admin.site.register(StudentAttendance)
admin.site.register(Exam)
admin.site.register(ExamNotification)
# Register your models here.

# admin.site.register(School)
# admin.site.register(CustomUser)
# admin.site.register(Staff)
# admin.site.register(Feature)
# admin.site.register(SchoolFeature)
# admin.site.register(LeaveTemplate)
# admin.site.register(LeaveRequest)
# admin.site.register(LeaveType)
# admin.site.register(LeavePerDay)
# admin.site.register(StaffRemainingLeave)    
# admin.site.register(AdmissionForm)    
# admin.site.register(FormSection)    
# admin.site.register(FormField)    
# admin.site.register(DocumentField)    
# admin.site.register(AdmissionDocument)    
# admin.site.register(Admission)
# admin.site.register(AttendanceLocation)
# admin.site.register(AttendanceTimeRule)
# admin.site.register(CertificateType)
# admin.site.register(Student)
# admin.site.register(CertificateRequest)
# admin.site.register(TempUser)