import logging
from .models import School, Holiday

logger = logging.getLogger(__name__)

DEFAULT_INDIAN_HOLIDAYS_2026 = [
    {
        "title": "New Year's Day",
        "name": "New Year's Day",
        "start_date": "2026-01-01",
        "end_date": "2026-01-01",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Celebration of the New Year. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Makar Sankranti / Pongal",
        "name": "Makar Sankranti / Pongal",
        "start_date": "2026-01-14",
        "end_date": "2026-01-14",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Harvest festival celebrated across India. School holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Republic Day",
        "name": "Republic Day",
        "start_date": "2026-01-26",
        "end_date": "2026-01-26",
        "event_type": "CELEBRATION",
        "is_holiday": True,
        "description": "National festival celebrating the Constitution of India. Flag hoisting ceremony at 8:00 AM.",
        "target_audience": "ALL",
        "location": "Main School Ground",
    },
    {
        "title": "Maha Shivratri",
        "name": "Maha Shivratri",
        "start_date": "2026-02-17",
        "end_date": "2026-02-17",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Auspicious Hindu festival. School holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Holi (Festival of Colors)",
        "name": "Holi (Festival of Colors)",
        "start_date": "2026-03-04",
        "end_date": "2026-03-04",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Festival of colors and spring celebration. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Eid-ul-Fitr (Ramzan Eid)",
        "name": "Eid-ul-Fitr (Ramzan Eid)",
        "start_date": "2026-03-20",
        "end_date": "2026-03-20",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Islamic festival marking the end of Ramadan. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Good Friday",
        "name": "Good Friday",
        "start_date": "2026-04-03",
        "end_date": "2026-04-03",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Christian holiday observing the crucifixion of Jesus Christ. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Dr. B.R. Ambedkar Jayanti",
        "name": "Dr. B.R. Ambedkar Jayanti",
        "start_date": "2026-04-14",
        "end_date": "2026-04-14",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Birth anniversary of Dr. B. R. Ambedkar, Father of the Indian Constitution.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Mahavir Jayanti",
        "name": "Mahavir Jayanti",
        "start_date": "2026-04-21",
        "end_date": "2026-04-21",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Birth anniversary of Lord Mahavira. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Maharashtra Day / Labour Day",
        "name": "Maharashtra Day / Labour Day",
        "start_date": "2026-05-01",
        "end_date": "2026-05-01",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "State formation day and International Workers' Day. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Buddha Purnima",
        "name": "Buddha Purnima",
        "start_date": "2026-05-02",
        "end_date": "2026-05-02",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Birth anniversary of Gautama Buddha. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Bakrid / Eid-ul-Adha",
        "name": "Bakrid / Eid-ul-Adha",
        "start_date": "2026-05-28",
        "end_date": "2026-05-28",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Feast of the Sacrifice observed by Muslims. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Muharram",
        "name": "Muharram",
        "start_date": "2026-06-26",
        "end_date": "2026-06-26",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "First month of Islamic calendar. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Independence Day",
        "name": "Independence Day",
        "start_date": "2026-08-15",
        "end_date": "2026-08-15",
        "event_type": "CELEBRATION",
        "is_holiday": True,
        "description": "Celebration of Indian Independence. Flag hoisting and patriotic cultural program.",
        "target_audience": "ALL",
        "location": "Main School Ground",
    },
    {
        "title": "Raksha Bandhan",
        "name": "Raksha Bandhan",
        "start_date": "2026-08-28",
        "end_date": "2026-08-28",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Celebration of sibling bonds and protection. School holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Janmashtami (Gokulashtami)",
        "name": "Janmashtami (Gokulashtami)",
        "start_date": "2026-09-04",
        "end_date": "2026-09-04",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Birth celebration of Lord Krishna and Dahi Handi festivity. School holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Ganesh Chaturthi",
        "name": "Ganesh Chaturthi",
        "start_date": "2026-09-15",
        "end_date": "2026-09-15",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Arrival of Lord Ganesha festival. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Eid-e-Milad (Milad-un-Nabi)",
        "name": "Eid-e-Milad (Milad-un-Nabi)",
        "start_date": "2026-09-24",
        "end_date": "2026-09-24",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Observance of the birthday of Islamic Prophet Muhammad. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Mahatma Gandhi Jayanti",
        "name": "Mahatma Gandhi Jayanti",
        "start_date": "2026-10-02",
        "end_date": "2026-10-02",
        "event_type": "CELEBRATION",
        "is_holiday": True,
        "description": "National festival commemorating the birth of the Father of the Nation. Swachhata Day.",
        "target_audience": "ALL",
        "location": "School Campus",
    },
    {
        "title": "Dussehra (Vijayadashami)",
        "name": "Dussehra (Vijayadashami)",
        "start_date": "2026-10-20",
        "end_date": "2026-10-20",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Victory of good over evil. Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Diwali Vacation",
        "name": "Diwali Vacation",
        "start_date": "2026-11-06",
        "end_date": "2026-11-12",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Deepawali festival, Laxmi Pujan, Govardhan Puja, and Bhai Dooj holidays. School closed.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Guru Nanak Jayanti",
        "name": "Guru Nanak Jayanti",
        "start_date": "2026-11-24",
        "end_date": "2026-11-24",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Birth anniversary of Guru Nanak Dev Ji (Gurpurab). Public holiday.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
    {
        "title": "Christmas Vacation",
        "name": "Christmas Vacation",
        "start_date": "2026-12-25",
        "end_date": "2026-12-31",
        "event_type": "HOLIDAY",
        "is_holiday": True,
        "description": "Christmas and Year-End school vacation. School resumes Jan 2.",
        "target_audience": "ALL",
        "location": "School-Wide",
    },
]

def seed_default_school_holidays(school):
    """Seed standard public holidays for a given school if they do not exist."""
    if not school:
        return 0
    
    count = 0
    for item in DEFAULT_INDIAN_HOLIDAYS_2026:
        # Check if holiday with same name/title and start_date exists for this school
        exists = Holiday.objects.filter(
            school=school,
            start_date=item["start_date"]
        ).filter(
            name__iexact=item["title"]
        ).exists()

        if not exists:
            Holiday.objects.create(
                school=school,
                name=item["name"],
                title=item["title"],
                start_date=item["start_date"],
                end_date=item.get("end_date") or item["start_date"],
                event_type=item.get("event_type", "HOLIDAY"),
                is_holiday=item.get("is_holiday", True),
                description=item.get("description", ""),
                target_audience=item.get("target_audience", "ALL"),
                location=item.get("location", "School-Wide"),
            )
            count += 1

    return count

def seed_default_holidays_for_all_schools():
    """Seed holidays for all active schools."""
    total = 0
    for school in School.objects.all():
        total += seed_default_school_holidays(school)
    return total
